[[constraint]]
  name = "github.com/uber/jaeger-client-go"
  version = "2.x"

[[constraint]]
  name = "gopkg.in/natefinch/lumberjack.v2"
  version = "2.x"

[prune]
  go-tests = true
  unused-packages = true
